[package]
name = "dymaxilang"
version = "0.1.0"
edition = "2021"

[features]
debug_gc = []
clobber_gc = []
decompile = []
trace_execution = []
local_map_scopes = []

[dependencies]
ordered-float = "4.5"
escape-bytes = "0.1.1"
